services:
  osrm-driving:
    build:
      context: ./driving
      dockerfile: Dockerfile
    container_name: osrm-driving
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - 127.0.0.1:5000:5000

  osrm-foot:
    build:
      context: ./foot
      dockerfile: Dockerfile
    container_name: osrm-foot
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - 127.0.0.1:5001:5000

  osrm-motorcycle:
    build:
      context: ./motorcycle
      dockerfile: Dockerfile
    container_name: osrm-motorcycle
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - 127.0.0.1:5002:5000
